/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyekbioskop;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Clarissa Angelia
 */
public class JFrame_Admin extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String url = "jdbc:mysql://localhost:3306/bioskop_ndut";
    String user;
    
    /**
     * Creates new form JFrame_Admin
     */
    public JFrame_Admin() {
        initComponents();
        //date format dd/mm/yy
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        jLabel_tanggal.setText(String.valueOf(dtf.format(now)));
        
        jButton_film1.setText("");
        jButton_film2.setText("");
        jButton_film3.setText("");
        jButton_film4.setText("");
        //date format yyyy-mm-dd
//        jLabel_tanggal.setText(String.valueOf(java.time.LocalDate.now()));

        try{
            //setup driver
            Class.forName("com.mysql.jdbc.Driver");
        } catch(ClassNotFoundException ex){
            System.out.println("mysql driver not found");
        }
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre";
            
            //set Statement
            pst = conn.prepareStatement(query);
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            //to generate image for home poster
            int count = 0;
            while(rs.next()){
                //Scale image
                ImageIcon film1 = new ImageIcon(rs.getString("poster"));
                Image temp = film1.getImage();
                Image imgscale1 = temp.getScaledInstance(jButton_film1.getWidth(), jButton_film1.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon scale1 = new ImageIcon(imgscale1);


                //set condition
                if(count==0){
                    jButton_film1.setIcon(scale1);
                    jLabel_film1.setText(rs.getString("judul"));
                }
                if(count==1){
                    jButton_film2.setIcon(scale1);
                    jLabel_film2.setText(rs.getString("judul"));

                }
                if(count==2){
                    jButton_film3.setIcon(scale1);
                    jLabel_film3.setText(rs.getString("judul"));
                }
                if(count==3){
                    jButton_film4.setIcon(scale1);
                    jLabel_film4.setText(rs.getString("judul"));
                }
                count+=1;
            }
                
        }catch (Exception ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
        
    }
    
    public void setUser(String admin){
        user = admin;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_film1 = new javax.swing.JLabel();
        jButton_film1 = new javax.swing.JButton();
        jLabel_film2 = new javax.swing.JLabel();
        jButton_film2 = new javax.swing.JButton();
        jLabel_film3 = new javax.swing.JLabel();
        jButton_film3 = new javax.swing.JButton();
        jLabel_film4 = new javax.swing.JLabel();
        jButton_film4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_keluar = new javax.swing.JMenu();
        jMenu_menu = new javax.swing.JMenu();
        jMenuItem_update = new javax.swing.JMenuItem();
        jMenuItem_laporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(818, 532));
        setMinimumSize(new java.awt.Dimension(818, 532));
        setPreferredSize(new java.awt.Dimension(818, 532));
        getContentPane().setLayout(null);

        jLabel_tanggal.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_tanggal.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_tanggal.setText("jLabel_tanggal");
        getContentPane().add(jLabel_tanggal);
        jLabel_tanggal.setBounds(511, 16, 274, 21);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 179, 44));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEDANG TAYANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 53, 810, 54);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 179, 44));
        jLabel2.setText("THEATER 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 130, 102, 27);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 179, 44));
        jLabel6.setText("THEATER 2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 130, 102, 27);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 179, 44));
        jLabel8.setText("THEATER 3");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 130, 102, 27);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 179, 44));
        jLabel9.setText("THEATER 4");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 130, 102, 27);

        jLabel_film1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_film1.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_film1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_film1.setText("film 1");
        jPanel1.add(jLabel_film1);
        jLabel_film1.setBounds(50, 410, 160, 21);

        jButton_film1.setForeground(new java.awt.Color(247, 179, 44));
        jButton_film1.setText("poster film 1");
        jButton_film1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film1);
        jButton_film1.setBounds(50, 170, 165, 225);

        jLabel_film2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_film2.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_film2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_film2.setText("film 2");
        jPanel1.add(jLabel_film2);
        jLabel_film2.setBounds(230, 410, 160, 21);

        jButton_film2.setForeground(new java.awt.Color(247, 179, 44));
        jButton_film2.setText("poster film 2");
        jButton_film2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film2);
        jButton_film2.setBounds(230, 170, 165, 225);

        jLabel_film3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_film3.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_film3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_film3.setText("film 3");
        jPanel1.add(jLabel_film3);
        jLabel_film3.setBounds(410, 410, 160, 21);

        jButton_film3.setForeground(new java.awt.Color(247, 179, 44));
        jButton_film3.setText("poster film 3");
        jButton_film3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film3);
        jButton_film3.setBounds(410, 170, 165, 225);

        jLabel_film4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_film4.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_film4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_film4.setText("film 4");
        jPanel1.add(jLabel_film4);
        jLabel_film4.setBounds(590, 410, 160, 21);

        jButton_film4.setForeground(new java.awt.Color(247, 179, 44));
        jButton_film4.setText("poster film 4");
        jButton_film4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film4);
        jButton_film4.setBounds(590, 170, 165, 225);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 510);

        jMenuBar1.setBackground(new java.awt.Color(247, 179, 44));
        jMenuBar1.setForeground(new java.awt.Color(168, 229, 186));

        jMenu_keluar.setForeground(new java.awt.Color(102, 0, 0));
        jMenu_keluar.setText("Keluar");
        jMenu_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_keluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_keluar);

        jMenu_menu.setBackground(new java.awt.Color(247, 179, 44));
        jMenu_menu.setForeground(new java.awt.Color(102, 0, 0));
        jMenu_menu.setText("Menu");

        jMenuItem_update.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_update.setBackground(new java.awt.Color(247, 179, 44));
        jMenuItem_update.setForeground(new java.awt.Color(102, 0, 0));
        jMenuItem_update.setText("Update Film");
        jMenuItem_update.setMaximumSize(new java.awt.Dimension(800, 550));
        jMenuItem_update.setMinimumSize(new java.awt.Dimension(800, 550));
        jMenuItem_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_updateActionPerformed(evt);
            }
        });
        jMenu_menu.add(jMenuItem_update);

        jMenuItem_laporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_laporan.setBackground(new java.awt.Color(247, 179, 44));
        jMenuItem_laporan.setForeground(new java.awt.Color(102, 0, 0));
        jMenuItem_laporan.setText("Laporan Transaksi");
        jMenuItem_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_laporanActionPerformed(evt);
            }
        });
        jMenu_menu.add(jMenuItem_laporan);

        jMenuBar1.add(jMenu_menu);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_updateActionPerformed
        // TODO add your handling code here:
        
        JFrame_update update = new JFrame_update();
        update.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItem_updateActionPerformed

    private void jMenu_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_keluarMouseClicked
        // TODO add your handling code here:

        int jawab = JOptionPane.showOptionDialog(this,
                "Ingin Keluar?",
                "Keluar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if (jawab == JOptionPane.YES_OPTION) {
            dispose();
        }
        
    }//GEN-LAST:event_jMenu_keluarMouseClicked

    private void jMenuItem_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_laporanActionPerformed
        // TODO add your handling code here:
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM user WHERE name=?";
//            
//            //open the statement if no condition
//            //Statement st = conn.createStatement();
//            
//            //handle result if no condition
//            //rs = st.executeQuery(query);
//            
//            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, user);      
            rs = pst.executeQuery();
            if(rs.next()){
               if(rs.getString("role").equals("superadmin")){
                   JFrame_Transaksi transaksi = new JFrame_Transaksi();
                   transaksi.setVisible(true);
                   dispose();
               }else{
                   JOptionPane.showMessageDialog(this, "You are not authorized!");
               }        
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jMenuItem_laporanActionPerformed

    private void jButton_film1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film1ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "1");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 1);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film1ActionPerformed

    private void jButton_film2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film2ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "2");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 2);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film2ActionPerformed

    private void jButton_film3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film3ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "3");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 3);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film3ActionPerformed

    private void jButton_film4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film4ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "4");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 4);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_film1;
    private javax.swing.JButton jButton_film2;
    private javax.swing.JButton jButton_film3;
    private javax.swing.JButton jButton_film4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_film1;
    private javax.swing.JLabel jLabel_film2;
    private javax.swing.JLabel jLabel_film3;
    private javax.swing.JLabel jLabel_film4;
    private javax.swing.JLabel jLabel_tanggal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_laporan;
    private javax.swing.JMenuItem jMenuItem_update;
    private javax.swing.JMenu jMenu_keluar;
    private javax.swing.JMenu jMenu_menu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
