/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyekbioskop;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Clarissa Angelia
 */
public class JFrame_Booking extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Booking
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String url = "jdbc:mysql://localhost:3306/bioskop_ndut";
    String Theater;
    public JFrame_Booking() {
        initComponents();
        
        //date format dd/mm/yy
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        jLabel_tanggal.setText(String.valueOf(dtf.format(now)));
        
        //date format yyyy-mm-dd
//        jLabel_tanggal.setText(String.valueOf(java.time.LocalDate.now()));

        try{
            //setup driver
            Class.forName("com.mysql.jdbc.Driver");
        } catch(ClassNotFoundException ex){
            System.out.println("mysql driver not found");
        }
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre";
            
            //set Statement
            pst = conn.prepareStatement(query);
          
            //handle the results
            rs = pst.executeQuery();
            
            int count = 0;
            while(rs.next()){
                //set condition
                if(count==0){
                    jButton_film1.setText(rs.getString("judul"));
                    jLabel_theater1.setText("THEATER " + rs.getString("id_theatre"));
                }
                if(count==1){
                    jButton_film2.setText(rs.getString("judul"));
                    jLabel_theater2.setText("THEATER " + rs.getString("id_theatre"));

                }
                if(count==2){
                    jButton_film3.setText(rs.getString("judul"));
                    jLabel_theater3.setText("THEATER " + rs.getString("id_theatre"));
                }
                if(count==3){
                    jButton_film4.setText(rs.getString("judul"));
                    jLabel_theater4.setText("THEATER " + rs.getString("id_theatre"));
                }
                count+=1;
            }
                
        }catch (Exception ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }

    public void detailfilm(){
        
        JFrame_DetailFilm df = new JFrame_DetailFilm();
        df.setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel_summary = new javax.swing.JLabel();
        jLabel_line2 = new javax.swing.JLabel();
        jLabel_line8 = new javax.swing.JLabel();
        jLabel_line9 = new javax.swing.JLabel();
        jButton_film1 = new javax.swing.JButton();
        jLabel_theater1 = new javax.swing.JLabel();
        jRadioButton_pagi1 = new javax.swing.JRadioButton();
        jRadioButton_malam1 = new javax.swing.JRadioButton();
        jRadioButton_siang1 = new javax.swing.JRadioButton();
        jButton_film2 = new javax.swing.JButton();
        jLabel_theater2 = new javax.swing.JLabel();
        jRadioButton_pagi2 = new javax.swing.JRadioButton();
        jRadioButton_siang2 = new javax.swing.JRadioButton();
        jRadioButton_malam2 = new javax.swing.JRadioButton();
        jButton_film3 = new javax.swing.JButton();
        jRadioButton_pagi3 = new javax.swing.JRadioButton();
        jRadioButton_siang3 = new javax.swing.JRadioButton();
        jLabel_theater3 = new javax.swing.JLabel();
        jRadioButton_malam3 = new javax.swing.JRadioButton();
        jButton_film4 = new javax.swing.JButton();
        jLabel_theater4 = new javax.swing.JLabel();
        jRadioButton_pagi4 = new javax.swing.JRadioButton();
        jRadioButton_siang4 = new javax.swing.JRadioButton();
        jRadioButton_malam4 = new javax.swing.JRadioButton();
        jButton_kembali = new javax.swing.JButton();
        jLabel_line10 = new javax.swing.JLabel();
        jLabel_line1 = new javax.swing.JLabel();
        jButton_selanjutnya = new javax.swing.JButton();
        jLabel_tanggal = new javax.swing.JLabel();
        jLabel_line5 = new javax.swing.JLabel();
        jLabel_line6 = new javax.swing.JLabel();
        jLabel_line7 = new javax.swing.JLabel();
        jLabel_line3 = new javax.swing.JLabel();
        jLabel_line4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(645, 685));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel_summary.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_summary.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_summary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_summary.setText("JUDUL - JAM");
        jPanel1.add(jLabel_summary);
        jLabel_summary.setBounds(190, 590, 250, 40);

        jLabel_line2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line2.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line2.setText("------------------------------------------------------------------");
        jPanel1.add(jLabel_line2);
        jLabel_line2.setBounds(0, 290, 630, 30);

        jLabel_line8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line8.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line8.setText("------------------------------------------------------------------");
        jPanel1.add(jLabel_line8);
        jLabel_line8.setBounds(0, 410, 630, 30);

        jLabel_line9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line9.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line9.setText("------------------------------------------------------------------");
        jPanel1.add(jLabel_line9);
        jLabel_line9.setBounds(0, 170, 630, 30);

        jButton_film1.setBackground(new java.awt.Color(247, 179, 44));
        jButton_film1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_film1.setForeground(new java.awt.Color(102, 0, 0));
        jButton_film1.setText("FILM 1");
        jButton_film1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_film1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film1);
        jButton_film1.setBounds(50, 80, 245, 45);

        jLabel_theater1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_theater1.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_theater1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_theater1.setText("THEATER #");
        jPanel1.add(jLabel_theater1);
        jLabel_theater1.setBounds(380, 80, 200, 45);

        jRadioButton_pagi1.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_pagi1);
        jRadioButton_pagi1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_pagi1.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_pagi1.setText("12.30");
        jRadioButton_pagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_pagi1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_pagi1);
        jRadioButton_pagi1.setBounds(110, 140, 100, 30);

        jRadioButton_malam1.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_malam1);
        jRadioButton_malam1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_malam1.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_malam1.setText("18.00");
        jRadioButton_malam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_malam1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_malam1);
        jRadioButton_malam1.setBounds(460, 140, 100, 30);

        jRadioButton_siang1.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_siang1);
        jRadioButton_siang1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_siang1.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_siang1.setText("15.00");
        jRadioButton_siang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_siang1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_siang1);
        jRadioButton_siang1.setBounds(290, 140, 100, 30);

        jButton_film2.setBackground(new java.awt.Color(247, 179, 44));
        jButton_film2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_film2.setForeground(new java.awt.Color(102, 0, 0));
        jButton_film2.setText("FILM 2");
        jButton_film2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_film2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film2);
        jButton_film2.setBounds(50, 200, 245, 45);

        jLabel_theater2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_theater2.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_theater2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_theater2.setText("THEATER #");
        jPanel1.add(jLabel_theater2);
        jLabel_theater2.setBounds(380, 200, 200, 45);

        jRadioButton_pagi2.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_pagi2);
        jRadioButton_pagi2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_pagi2.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_pagi2.setText("12.30");
        jRadioButton_pagi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_pagi2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_pagi2);
        jRadioButton_pagi2.setBounds(110, 260, 100, 30);

        jRadioButton_siang2.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_siang2);
        jRadioButton_siang2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_siang2.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_siang2.setText("15.00");
        jRadioButton_siang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_siang2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_siang2);
        jRadioButton_siang2.setBounds(290, 260, 100, 30);

        jRadioButton_malam2.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_malam2);
        jRadioButton_malam2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_malam2.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_malam2.setText("18.00");
        jRadioButton_malam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_malam2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_malam2);
        jRadioButton_malam2.setBounds(460, 260, 100, 30);

        jButton_film3.setBackground(new java.awt.Color(247, 179, 44));
        jButton_film3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_film3.setForeground(new java.awt.Color(102, 0, 0));
        jButton_film3.setText("FILM 3");
        jButton_film3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_film3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film3);
        jButton_film3.setBounds(50, 320, 245, 45);

        jRadioButton_pagi3.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_pagi3);
        jRadioButton_pagi3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_pagi3.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_pagi3.setText("12.30");
        jRadioButton_pagi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_pagi3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_pagi3);
        jRadioButton_pagi3.setBounds(110, 380, 100, 30);

        jRadioButton_siang3.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_siang3);
        jRadioButton_siang3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_siang3.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_siang3.setText("15.00");
        jRadioButton_siang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_siang3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_siang3);
        jRadioButton_siang3.setBounds(290, 380, 100, 30);

        jLabel_theater3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_theater3.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_theater3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_theater3.setText("THEATER #");
        jPanel1.add(jLabel_theater3);
        jLabel_theater3.setBounds(380, 320, 200, 45);

        jRadioButton_malam3.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_malam3);
        jRadioButton_malam3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_malam3.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_malam3.setText("18.00");
        jRadioButton_malam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_malam3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_malam3);
        jRadioButton_malam3.setBounds(460, 380, 100, 30);

        jButton_film4.setBackground(new java.awt.Color(247, 179, 44));
        jButton_film4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_film4.setForeground(new java.awt.Color(102, 0, 0));
        jButton_film4.setText("FILM 4");
        jButton_film4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_film4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_film4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_film4);
        jButton_film4.setBounds(50, 440, 245, 45);

        jLabel_theater4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_theater4.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_theater4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_theater4.setText("THEATER #");
        jPanel1.add(jLabel_theater4);
        jLabel_theater4.setBounds(380, 440, 200, 45);

        jRadioButton_pagi4.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_pagi4);
        jRadioButton_pagi4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_pagi4.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_pagi4.setText("12.30");
        jRadioButton_pagi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_pagi4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_pagi4);
        jRadioButton_pagi4.setBounds(110, 500, 100, 30);

        jRadioButton_siang4.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_siang4);
        jRadioButton_siang4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_siang4.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_siang4.setText("15.00");
        jRadioButton_siang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_siang4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_siang4);
        jRadioButton_siang4.setBounds(290, 500, 100, 30);

        jRadioButton_malam4.setBackground(new java.awt.Color(102, 0, 0));
        buttonGroup1.add(jRadioButton_malam4);
        jRadioButton_malam4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton_malam4.setForeground(new java.awt.Color(247, 179, 44));
        jRadioButton_malam4.setText("18.00");
        jRadioButton_malam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_malam4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_malam4);
        jRadioButton_malam4.setBounds(460, 500, 100, 30);

        jButton_kembali.setBackground(new java.awt.Color(247, 179, 44));
        jButton_kembali.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton_kembali.setForeground(new java.awt.Color(102, 0, 0));
        jButton_kembali.setText("KEMBALI");
        jButton_kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_kembali);
        jButton_kembali.setBounds(20, 590, 160, 38);

        jLabel_line10.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line10.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line10.setText("============================================");
        jPanel1.add(jLabel_line10);
        jLabel_line10.setBounds(0, 50, 630, 30);

        jLabel_line1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line1.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line1.setText("============================================");
        jPanel1.add(jLabel_line1);
        jLabel_line1.setBounds(0, 530, 630, 30);

        jButton_selanjutnya.setBackground(new java.awt.Color(247, 179, 44));
        jButton_selanjutnya.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton_selanjutnya.setForeground(new java.awt.Color(102, 0, 0));
        jButton_selanjutnya.setText("SELANJUTNYA");
        jButton_selanjutnya.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_selanjutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selanjutnyaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_selanjutnya);
        jButton_selanjutnya.setBounds(450, 590, 160, 38);

        jLabel_tanggal.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_tanggal.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_tanggal.setText("jLabel_tanggal");
        jPanel1.add(jLabel_tanggal);
        jLabel_tanggal.setBounds(390, 20, 225, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 650);

        jLabel_line5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line5.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line5.setText("------------------------------------------------------------------");
        getContentPane().add(jLabel_line5);
        jLabel_line5.setBounds(0, 170, 630, 30);

        jLabel_line6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line6.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line6.setText("------------------------------------------------------------------");
        getContentPane().add(jLabel_line6);
        jLabel_line6.setBounds(0, 170, 630, 30);

        jLabel_line7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line7.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line7.setText("------------------------------------------------------------------");
        getContentPane().add(jLabel_line7);
        jLabel_line7.setBounds(0, 170, 630, 30);

        jLabel_line3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line3.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line3.setText("============================================");
        getContentPane().add(jLabel_line3);
        jLabel_line3.setBounds(0, 50, 630, 30);

        jLabel_line4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel_line4.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_line4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_line4.setText("============================================");
        getContentPane().add(jLabel_line4);
        jLabel_line4.setBounds(0, 50, 630, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_siang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_siang1ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film1.getText() + "-" + jRadioButton_siang1.getText());
        Theater = "THEATER 1";
    }//GEN-LAST:event_jRadioButton_siang1ActionPerformed

    private void jRadioButton_siang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_siang2ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film2.getText() + "-" + jRadioButton_siang2.getText());
        Theater = "THEATER 2";
    }//GEN-LAST:event_jRadioButton_siang2ActionPerformed

    private void jRadioButton_siang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_siang3ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film3.getText() + "-" + jRadioButton_siang3.getText());
        Theater = "THEATER 3";
    }//GEN-LAST:event_jRadioButton_siang3ActionPerformed

    private void jRadioButton_siang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_siang4ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film4.getText() + "-" + jRadioButton_siang4.getText());
        Theater = "THEATER 4";
    }//GEN-LAST:event_jRadioButton_siang4ActionPerformed

    private void jButton_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kembaliActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_jButton_kembaliActionPerformed

    private void jButton_film2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film2ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "2");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 2);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film2ActionPerformed

    private void jRadioButton_pagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_pagi1ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film1.getText() + "-" + jRadioButton_pagi1.getText());
        Theater = "THEATER 1";
    }//GEN-LAST:event_jRadioButton_pagi1ActionPerformed

    private void jButton_selanjutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selanjutnyaActionPerformed
        // TODO add your handling code here:
        
        JFrame_Kursi kursi = new JFrame_Kursi();
        String text = jLabel_summary.getText();
        kursi.setTitle(text, Theater);
        kursi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_selanjutnyaActionPerformed

    private void jButton_film1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film1ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "1");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 1);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film1ActionPerformed

    private void jButton_film3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film3ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "3");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 3);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film3ActionPerformed

    private void jButton_film4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_film4ActionPerformed
        // TODO add your handling code here:
        
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM theatre WHERE id_theatre=? ";
            
            //open the statement if no condition
            //Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, "4");
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                String imageref = rs.getString("poster");
                String judul = rs.getString("judul");
                String sinop = rs.getString("sinopsis");
                JFrame_DetailFilm df = new JFrame_DetailFilm();
                df.setAtt(judul, imageref, sinop, 4);
                
                df.setVisible(true);            
            } else {
            JOptionPane.showMessageDialog(this, "Error Occured!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
        
    }//GEN-LAST:event_jButton_film4ActionPerformed

    private void jRadioButton_malam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_malam1ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film1.getText() + "-" + jRadioButton_malam1.getText());
        Theater = "THEATER 1";
    }//GEN-LAST:event_jRadioButton_malam1ActionPerformed

    private void jRadioButton_malam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_malam2ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film2.getText() + "-" + jRadioButton_malam2.getText());
        Theater = "THEATER 2";
    }//GEN-LAST:event_jRadioButton_malam2ActionPerformed

    private void jRadioButton_malam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_malam3ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film3.getText() + "-" + jRadioButton_malam3.getText());
        Theater = "THEATER 3";
    }//GEN-LAST:event_jRadioButton_malam3ActionPerformed

    private void jRadioButton_pagi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_pagi3ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film3.getText() + "-" + jRadioButton_pagi3.getText());
        Theater = "THEATER 3";
    }//GEN-LAST:event_jRadioButton_pagi3ActionPerformed

    private void jRadioButton_pagi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_pagi2ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film2.getText() + "-" + jRadioButton_pagi2.getText());
        Theater = "THEATER 2";
    }//GEN-LAST:event_jRadioButton_pagi2ActionPerformed

    private void jRadioButton_pagi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_pagi4ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film4.getText() + "-" + jRadioButton_pagi4.getText());
        Theater = "THEATER 4";
    }//GEN-LAST:event_jRadioButton_pagi4ActionPerformed

    private void jRadioButton_malam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_malam4ActionPerformed
        // TODO add your handling code here:
        jLabel_summary.setText(jButton_film4.getText() + "-" + jRadioButton_malam4.getText());
        Theater = "THEATER 4";
    }//GEN-LAST:event_jRadioButton_malam4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton_film1;
    private javax.swing.JButton jButton_film2;
    private javax.swing.JButton jButton_film3;
    private javax.swing.JButton jButton_film4;
    private javax.swing.JButton jButton_kembali;
    private javax.swing.JButton jButton_selanjutnya;
    private javax.swing.JLabel jLabel_line1;
    private javax.swing.JLabel jLabel_line10;
    private javax.swing.JLabel jLabel_line2;
    private javax.swing.JLabel jLabel_line3;
    private javax.swing.JLabel jLabel_line4;
    private javax.swing.JLabel jLabel_line5;
    private javax.swing.JLabel jLabel_line6;
    private javax.swing.JLabel jLabel_line7;
    private javax.swing.JLabel jLabel_line8;
    private javax.swing.JLabel jLabel_line9;
    private javax.swing.JLabel jLabel_summary;
    private javax.swing.JLabel jLabel_tanggal;
    private javax.swing.JLabel jLabel_theater1;
    private javax.swing.JLabel jLabel_theater2;
    private javax.swing.JLabel jLabel_theater3;
    private javax.swing.JLabel jLabel_theater4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_malam1;
    private javax.swing.JRadioButton jRadioButton_malam2;
    private javax.swing.JRadioButton jRadioButton_malam3;
    private javax.swing.JRadioButton jRadioButton_malam4;
    private javax.swing.JRadioButton jRadioButton_pagi1;
    private javax.swing.JRadioButton jRadioButton_pagi2;
    private javax.swing.JRadioButton jRadioButton_pagi3;
    private javax.swing.JRadioButton jRadioButton_pagi4;
    private javax.swing.JRadioButton jRadioButton_siang1;
    private javax.swing.JRadioButton jRadioButton_siang2;
    private javax.swing.JRadioButton jRadioButton_siang3;
    private javax.swing.JRadioButton jRadioButton_siang4;
    // End of variables declaration//GEN-END:variables
}
