/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyekbioskop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Clarissa Angelia
 */
public class JFrame_Login extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Login
     */
    public JFrame_Login() {
        initComponents();
        
        //date format dd/mm/yy
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        jLabel_tanggal.setText(String.valueOf(dtf.format(now)));
        
        //date format yyyy-mm-dd
//        jLabel_tanggal.setText(String.valueOf(java.time.LocalDate.now()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_login = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jLabel_tanggal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(615, 435));
        setMinimumSize(new java.awt.Dimension(615, 435));
        getContentPane().setLayout(null);

        jLabel_login.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel_login.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login.setText("LOG IN");
        getContentPane().add(jLabel_login);
        jLabel_login.setBounds(0, 53, 600, 63);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 179, 44));
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 134, 108, 22);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 179, 44));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 179, 119, 22);

        jTextField_username.setBackground(new java.awt.Color(247, 179, 44));
        jTextField_username.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(102, 0, 0));
        jTextField_username.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        getContentPane().add(jTextField_username);
        jTextField_username.setBounds(252, 134, 260, 25);

        jPasswordField_password.setBackground(new java.awt.Color(247, 179, 44));
        jPasswordField_password.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jPasswordField_password.setForeground(new java.awt.Color(102, 0, 0));
        jPasswordField_password.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, java.awt.Color.orange));
        getContentPane().add(jPasswordField_password);
        jPasswordField_password.setBounds(252, 179, 260, 25);

        jButton_login.setBackground(new java.awt.Color(247, 179, 44));
        jButton_login.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(102, 0, 0));
        jButton_login.setText("LOG IN");
        jButton_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login);
        jButton_login.setBounds(229, 241, 140, 33);

        jButton_back.setBackground(new java.awt.Color(247, 179, 44));
        jButton_back.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton_back.setForeground(new java.awt.Color(102, 0, 0));
        jButton_back.setText("BACK");
        jButton_back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(229, 294, 140, 33);

        jLabel_tanggal.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_tanggal.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_tanggal.setText("jLabel_tanggal");
        getContentPane().add(jLabel_tanggal);
        jLabel_tanggal.setBounds(360, 16, 225, 21);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        String uname = jTextField_username.getText();
        String pass = jPasswordField_password.getText();
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        String url = "jdbc:mysql://localhost:3306/bioskop_ndut";
        try{
            //setup driver
            Class.forName("com.mysql.jdbc.Driver");
        } catch(ClassNotFoundException ex){
            System.out.println("mysql driver not found");
        }
        try{
            //database:bioskop_ndut, user:root, pwd:None
            conn = DriverManager.getConnection(url, "root", "");
            //create query
            String query = "SELECT * FROM user WHERE name=? AND pass=? ";
            
            //open the statement if no condition
//            Statement st = conn.createStatement();
            
            //handle result if no condition
            //rs = st.executeQuery(query);
            
            //set Statement
            pst = conn.prepareStatement(query);
            pst.setString(1, uname);
            pst.setString(2, pass);
          
//            System.out.println(query);
//            System.out.println(pst);
            
            //handle the results
            rs = pst.executeQuery();
            
            if(rs.next()){
                dispose();
                JOptionPane.showMessageDialog(null, "Welcome " + uname);
                JFrame_Admin admin = new JFrame_Admin();
                admin.setUser(uname);
                admin.setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "Username/Password Salah!");
            }
        }catch (SQLException ex){
            System.out.println("not connected");
            System.out.println(ex);
                    
        }
       
    }//GEN-LAST:event_jButton_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_tanggal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
