/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyekbioskop;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Clarissa Angelia
 */
public class JFrame_DetailFilm extends javax.swing.JFrame {

    /** Creates new form JFrame_DetailFilm */
    public JFrame_DetailFilm() {
        initComponents();
    }

    //method to set new value
    public void setAtt(String judul, String imgurl, String sinop, int theatre){
        //set judul, sinop, dan theatre
        jLabel_judul.setText(judul); 
        jTextArea_sinopsis.setText(sinop);
        jLabel_theater.setText("Theater " + theatre);
        
        //Scaling image poster to fit jlable
        ImageIcon poster = new ImageIcon(imgurl);
        Image img = poster.getImage();
        Image postscale = img.getScaledInstance(jLabel_poster.getWidth(), jLabel_poster.getHeight(), Image.SCALE_SMOOTH);
        
        //to convert image to imageicon
        ImageIcon scaled = new ImageIcon(postscale);
        //set imageicon
        jLabel_poster.setIcon(scaled);
       
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_judul = new javax.swing.JLabel();
        jLabel_poster = new javax.swing.JLabel();
        jLabel_theater = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_sinopsis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(615, 580));
        setMinimumSize(new java.awt.Dimension(615, 580));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(null);

        jLabel_judul.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel_judul.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_judul.setText("jLabel_judul");
        jPanel1.add(jLabel_judul);
        jLabel_judul.setBounds(290, 100, 290, 90);

        jLabel_poster.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel_poster.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_poster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_poster.setText("jLabel_poster");
        jPanel1.add(jLabel_poster);
        jLabel_poster.setBounds(20, 100, 260, 410);

        jLabel_theater.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel_theater.setForeground(new java.awt.Color(247, 179, 44));
        jLabel_theater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_theater.setText("jLabel_theater");
        jPanel1.add(jLabel_theater);
        jLabel_theater.setBounds(0, 20, 600, 60);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(106, 21));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(106, 21));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(106, 21));

        jTextArea_sinopsis.setEditable(false);
        jTextArea_sinopsis.setColumns(20);
        jTextArea_sinopsis.setLineWrap(true);
        jTextArea_sinopsis.setRows(5);
        jScrollPane1.setViewportView(jTextArea_sinopsis);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 200, 290, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_DetailFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_DetailFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_DetailFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_DetailFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_DetailFilm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_judul;
    private javax.swing.JLabel jLabel_poster;
    private javax.swing.JLabel jLabel_theater;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_sinopsis;
    // End of variables declaration//GEN-END:variables

}
